#!/bin/bash

# Auto-Build Environment Setup - PocketBase Update
# Generated by Planner Agent

set -e

echo "========================================"
echo "PocketBase Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# ENVIRONMENT CHECK
# ============================================

echo ""
echo "Checking environment..."

# Check for required environment variables
if [ -z "$SUPERUSER_EMAIL" ] || [ -z "$SUPERUSER_PASSWORD" ]; then
    echo -e "${YELLOW}Warning: SUPERUSER_EMAIL or SUPERUSER_PASSWORD not set${NC}"
    echo "These are optional for development but required for migration"
fi

# Check for Go installation
if ! command -v go &> /dev/null; then
    echo -e "${RED}Error: Go is not installed${NC}"
    exit 1
fi

# Check for Docker installation
if ! command -v docker-compose &> /dev/null; then
    echo -e "${YELLOW}Warning: docker-compose not found - Docker deployment will not work${NC}"
fi

# ============================================
# OPTION: Local Development or Docker
# ============================================

echo ""
echo "Choose deployment mode:"
echo "  1) Local Go development (./pocketbase serve)"
echo "  2) Docker deployment (docker-compose up)"
echo ""
read -p "Enter choice [1-2]: " choice

case $choice in
    1)
        echo ""
        echo "========================================"
        echo "Starting Local Development Mode"
        echo "========================================"
        echo ""

        # Build PocketBase binary
        echo "Building PocketBase..."
        go build -o pocketbase main.go

        if [ ! -f pocketbase ]; then
            echo -e "${RED}Build failed${NC}"
            exit 1
        fi

        echo -e "${GREEN}Build successful${NC}"
        echo ""

        # Start PocketBase
        echo "Starting PocketBase..."
        echo ""
        ./pocketbase serve --http=0.0.0.0:8090
        ;;

    2)
        echo ""
        echo "========================================"
        echo "Starting Docker Mode"
        echo "========================================"
        echo ""

        # Check if services are already running
        if docker-compose ps | grep -q "Up"; then
            echo -e "${YELLOW}Services already running. Stopping first...${NC}"
            docker-compose down
        fi

        # Start services
        echo "Starting Docker services..."
        docker-compose up -d

        # Wait for PocketBase
        wait_for_service 8090 "PocketBase"

        echo ""
        echo "Checking service status..."
        docker-compose ps
        ;;

    *)
        echo -e "${RED}Invalid choice${NC}"
        exit 1
        ;;
esac

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  PocketBase API:    http://localhost:8090/api/"
echo "  Admin Dashboard:   http://localhost:8090/_/"
echo "  Health Check:      http://localhost:8090/health"
echo "  API Docs:          http://localhost:8090/api/docs"
echo ""
echo "Environment Variables:"
echo "  SUPERUSER_EMAIL:    ${SUPERUSER_EMAIL:-<not set>}"
echo "  SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD:+<set>}${SUPERUSER_PASSWORD:-<not set>}"
echo ""
echo "Useful Commands:"
echo "  - Stop services:     docker-compose down"
echo "  - View logs:         docker-compose logs -f pocketbase"
echo "  - Run migrations:    docker-compose up migrate"
echo "  - Run tests:         go test ./tests/... -v"
echo ""
